### ISSUE TITLE
Teamにいない人のPRもpreviewしたい

### ISSUE THREAD

**Issue by Qs-F** [4-design/for-ui#913]
現状CloudflareはTeamにいない人のPRをpreview deployしてくれない ([参考](https://github.com/cloudflare/cloudflare-docs/pull/2880))

別途GitHub Actionsでdeployするように変更したほうがいいかもしれない

**Comment by Qs-F** [comment]
```yml
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: yarn --cwd ./packages/for-ui build-storybook

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: YOUR_ACCOUNT_ID
          projectName: YOUR_PROJECT_NAME
          directory: YOUR_ASSET_DIRECTORY
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```
